### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by andreasjacobsen93** [arcreative/xbox-on#3]
xbox-on --help, gives the following error:
/usr/local/bin/xbox-on: line 1: syntax error near unexpected token `'colors'´
/usr/local/bin/xbox-on: line 1:`require('colors');'

**Comment by arcreative** [comment]
This has been fixed, but I forgot to publish the latest version to npm--will do so shortly :-)

**Comment by arcreative** [comment]
Fixed, `npm install -g xbox-on` should get you up and running :-)
