### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by sdorilas** [arcreative/xbox-on#4]
I am new to using nodes. I'm currently working with homebridge-Xbox-one. Xbox-on is the only dependency. I've added Xbox one to my accessories in the config file and I have installed the Xbox-on  using npm install -g Xbox. Not sure if I'm missing any config files or if I need to do additional steps. However whenever I request to have my Xbox turn on, I see the request through terminal but Xbox never turns on. Any help would be greatly appreciated. Thank you!!!

**Comment by arcreative** [comment]
Assuming that you have the correct IP address and Live ID, it must be mentioned that Xbox WoL reliability is... just plain awful.  Even their own smartglass app doesn't really work, so I'm assuming this is probably for the same reasons that nothing else made by Microsoft seems to work correctly.

Only thing I can suggest is to add "tries" to your accessory config and set it to something higher than 5 (the default).  It will just blindly send more dgrams to the Xbox, and hopefully one of them will work.  The other thing you can try is to make sure that your Xbox is using a wired ethernet connection, if possible.  Final thing to confirm is that you're using the "instant on" setting on the Xbox, as it won't be listening to the dgrams if the xbox is fully off.  

I'll confirm mine still works and re-open if it doesn't, thanks for the information :-)

**Comment by sdorilas** [comment]
Thank you so much for getting back to me. Now pardon my ignorance (again I'm new to this), but where exactly do I add "tries" or change the default. Thank you in advance.

**Comment by arcreative** [comment]
In your homebridge `config.json` file:

```
...
"accessories": [
    {
      "accessory": "Xbox",
      "name": "Xbox",
      "ipAddress": "<your XBox IP address here>",
      "liveId": "<your live ID here>",
      "tries": 10
    }
]
...
```

I've confirmed it still working on my system, but I had to hard reset it first by holding the power button, then boot it up and down normally.

**Comment by sdorilas** [comment]
Thank you so much!! You've been a great help. I'll try that now. Tomorrow is the Nest -- wish me luck :)

**Comment by arcreative** [comment]
Good luck, Nest should be easier :-)
