### ISSUE TITLE
Any work happening with this? I'd love to help

### ISSUE THREAD

**Issue by johnypony3** [arcreative/xbox-on#5]
Hi, I'm also a developer, and would love to be able to turn off the device. How did you get the payload?

**Comment by arcreative** [comment]
Unfortunately, it looks like Microsoft hasn't enabled any functionality outside of turning the Xbox on.  There are additional proprietary functions like the ones used by the smart glass app, but they all appear to be encrypted.  

This module is a port of the original python version, and the payload was obtained using wireshark and a lot of trial and error.

Will definitely update this module to include additional functions if possible, but I'm afraid we're kinda stuck for now!

**Comment by arcreative** [comment]
And thanks for the offer, would love to collaborate if any other news comes up!

**Comment by johnypony3** [comment]
Thanks for such a quick reply. I tried to use burp as a proxy but because
it's hitting the IP it's not doing the man in the middle attack to see the
payloads.

**Comment by arcreative** [comment]
Not sure, my network-level foo is not so strong lately :-)
