### ISSUE TITLE
Add powerOff, start an App etc. 

### ISSUE THREAD

**Issue by WeeJeWel** [arcreative/xbox-on#6]
Great module! Have you looked into other commands when the Xbox is powered on? The SmartGlass app seems to be able to control much more.

**Comment by arcreative** [comment]
Smartglass is able to access proprietary, encrypted API functionality, which Microsoft hasn't allowed developers access to.  So unfortunately we're stuck :-(

**Comment by WeeJeWel** [comment]
Hm, I've read through the android app once and they're using a library that we should be able to create a node binding to by reverse engineering the android app. Actually the poweron function is in there as well..

I'll let you know if I've made any progress with it!

**Comment by arcreative** [comment]
Which android app?  And which library?

**Comment by WeeJeWel** [comment]
This app: https://play.google.com/store/apps/details?id=com.microsoft.xboxone.smartglass&hl=en

It contains multiple native libraries (.so files), I recall from memory that it was `libSmartGlassCore` that did the powerOn handling.

**Comment by WeeJeWel** [comment]
![screen shot 2016-09-17 at 19 58 02](https://cloud.githubusercontent.com/assets/319873/18610023/0f966a9c-7d11-11e6-91a8-fe8c7505feaa.png)

I have 0 experience with decompiling native code but this shows that it should be possible :-)
