### ISSUE TITLE
FIx payload and LiveID length

### ISSUE THREAD

**Issue by Schamper** [arcreative/xbox-on#7]
See https://github.com/Schamper/xbox-remote-power/commit/cd9a03ba3b6a3ef21cc9d428ca5910975b05bd17

**Comment by arcreative** [comment]
What's the update for?  It works currently, is there a reason to change it?

**Comment by Schamper** [comment]
Theoretically, if a LiveID's length != 16 bytes, the packet will be dismissed as the size fields won't match with the actual contents of the packet. However, I don't actually have proof that LiveID's aren't fixed size, so consider this a fix for an edge case if it turns out that a LiveID can be either longer or shorter than 16 bytes.

**Comment by arcreative** [comment]
How did you figure out the header included the length?  Is it possible that those bits just coincidentally matched?  Will throw together a PR soon, thanks for bringing it up!

**Comment by Schamper** [comment]
Let's just say that I know for sure that's the length field ;)

**Comment by edwardmeshuris** [comment]
> Let's just say that I know for sure that's the length field ;)

Bond, James Bond :D

**Comment by arcreative** [comment]
Welllllll I fixed this, but it looks like the new Buffer class methods don't work, at least on node 5.9.0.  Will try to patch that up.

**Comment by arcreative** [comment]
Ok fixed :-)
